### PR TITLE
Fix/ble timeout Merge

### PR DESCRIPTION
**Pull request by IoTPanic**
I originally brought a piece of code up to documentation, but than I found removing the loop in commit 4e2bce3 brought a much better experience. Also, the JSON buffer was way too small for my WiFi config and just wasnt working at all until I made it larger. I was able to configure and use 22x22 panel through the app.

### CODE REVIEW

**Comment by martinberlin** [comment]
Looks good, thanks for the JSON fix, makes total sense. About BLE_WAIT_FOR_CONFIG can you re-configure after setting such a low wait time? 
I though that even if it's already connected someone could need to reconfigure later

Update: Now I see, you added a delay(1000), so if it works alright is much better.

**Review by martinberlin — COMMENTED** [review]
Looks good, will test tonight and merge

**Review by martinberlin — APPROVED** [review]

**Comment by IoTPanic** [comment]
I removed the loop using BLE_WAIT_FOR_CONFIG completly in the second commit. I found it to work a lot better just using the bluetooth code in main().

**Review by martinberlin — APPROVED** [review]
Merged

**Comment by martinberlin** [comment]
Sorry but I had to revert: https://github.com/martinberlin/udpx/pull/11/commits/4e2bce319c665e69ba3c47d0ef079f6f57a6da7d

My idea here is that the user that wants to switch over different networks even in the same place has at least some seconds to reset credentials. Something you cannot do if you are attached to WiFi on the start. 
But renamed the config variable to: 
BLE_SECONDS_WAIT_FOR_CONFIG
(Is in Config.h not in main) And you can just set it to zero if you want to have a fast boot.

Maybe there is a smarter way to do it. But otherwise, if the user sends a bad password, enters in a reset loop all the time. A cool way will be to trigger this wait only with a button or something. 
But without some kind of hardware interaction must be a wait somewhere, or a very well designed method, that after 2 connection fails, defaults to wait for config mode. Let's think about it. I see your intention and also don't like it the way it is.
 Thanks for the Json stuff, very cool!

**Pull request merged**
